### ISSUE TITLE
Since update cameras show as disabled and homebridge crashes when trying to access camera via home.app macos

### ISSUE THREAD

**Issue by AtriskAlpha** [colinbendell/homebridge-blink-for-home#108]
So. I had the old version and it worked fine, I could see the two Blink cameras video, and it was just fine for my needs. Today I updated to the new version and the cameras only show up as disabled. Also, I think that the new version is crashing home bridge every time I try to view the cameras in the home app. I have attached the log below. Any help as to how to resolve this would be appreciated.

[08/04/2022, 19:29:25] Got SIGTERM, shutting down Homebridge...
[08/04/2022, 19:29:30] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[08/04/2022, 19:29:35] [HB Supervisor] Restarting Homebridge...
[08/04/2022, 19:29:35] [HB Supervisor] Starting Homebridge with extra flags: -I
[08/04/2022, 19:29:35] [HB Supervisor] Started Homebridge v1.4.0 with PID: 2391
[08/04/2022, 19:29:37] Loaded config.json with 0 accessories and 3 platforms.
[08/04/2022, 19:29:37] Loaded 3 cached accessories from cachedAccessories.
[08/04/2022, 19:29:38] ---
[08/04/2022, 19:29:40] Loaded plugin: homebridge-blink-for-home@3.9.0
[08/04/2022, 19:29:40] Registering platform 'homebridge-blink-for-home.Blink'
[08/04/2022, 19:29:40] ---
[08/04/2022, 19:29:40] Loaded plugin: homebridge-camera-ffmpeg@3.1.4
[08/04/2022, 19:29:40] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[08/04/2022, 19:29:40] ---
[08/04/2022, 19:29:41] Loaded plugin: homebridge-config-ui-x@4.42.0
[08/04/2022, 19:29:41] Registering platform 'homebridge-config-ui-x.config'
[08/04/2022, 19:29:41] ---
[08/04/2022, 19:29:41] Loading 3 platforms...
[08/04/2022, 19:29:41] [Config] Initializing config platform...
[08/04/2022, 19:29:41] [Config] Running in Service Mode
[08/04/2022, 19:29:41] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[08/04/2022, 19:29:41] [Blink] Initializing Blink platform...
[08/04/2022, 19:29:41] [Camera FFmpeg] [WyzePatio] Configuring unbridged accessory...
[08/04/2022, 19:29:41] [Blink] Init Blink
Setup Payload:
X-HM://00246MC2H4RXT
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

┌────────────┐     
xxx-xx-xxxx
└────────────┘

[08/04/2022, 19:29:42] WyzePatio ED0D is running on port 42075.
[08/04/2022, 19:29:42] Please add [WyzePatio ED0D] manually in Home app. Setup Code: xxxxxxxxxx
[08/04/2022, 19:29:42] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 306F) is running on port 51382.
[08/04/2022, 19:29:43] [Blink] ADD: Blink:Network:95669
[08/04/2022, 19:29:43] [Blink] ADD: Blink:Network:95669:Camera:236341
[08/04/2022, 19:29:43] [Blink] ADD: Blink:Network:95669:Camera:236364

all looks good then if I try to access the camera in the home app i get this. and shortly it reboots.

[08/04/2022, 19:30:51] [Blink] TypeError: Cannot read properties of undefined (reading 'proxyServer')
at BlinkCameraDelegate.handleStreamRequest (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/blink-camera-deligate.js:240:31)
at RTPStreamManagement._handleStopStream (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:963:19)
at RTPStreamManagement._handleSelectedStreamConfigurationWrite (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:751:12)
at SelectedRTPStreamConfiguration.emit (node:events:390:28)
at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1725:16
at new Promise ()
at SelectedRTPStreamConfiguration. (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1723:14)
at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
[08/04/2022, 19:31:00] [Blink] TypeError: Cannot read properties of undefined (reading 'proxyServer')
at BlinkCameraDelegate.handleStreamRequest (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/blink-camera-deligate.js:240:31)
at RTPStreamManagement._handleStopStream (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:963:19)
at RTPStreamManagement._handleSelectedStreamConfigurationWrite (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:751:12)
at SelectedRTPStreamConfiguration.emit (node:events:390:28)
at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1725:16
at new Promise ()
at SelectedRTPStreamConfiguration. (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1723:14)
at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
[08/04/2022, 19:31:28] [Blink] LiveView Stream: undefined
[08/04/2022, 19:31:28] Error: Audio was enabled but not supplied in PrepareStreamResponse!
at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1124:13)
at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1094:16
at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
at BlinkCameraDelegate.prepareStream (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/blink-camera-deligate.js:132:9)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
[08/04/2022, 19:31:28] Got SIGTERM, shutting down Homebridge...
[08/04/2022, 19:31:28] [Blink] LiveView Stream: undefined
[08/04/2022, 19:31:28] Error: Audio was enabled but not supplied in PrepareStreamResponse!
at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1124:13)
at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1094:16
at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
at BlinkCameraDelegate.prepareStream (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/blink-camera-deligate.js:132:9)
[08/04/2022, 19:31:33] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[08/04/2022, 19:31:38] [HB Supervisor] Restarting Homebridge...
[08/04/2022, 19:31:38] [HB Supervisor] Starting Homebridge with extra flags: -I
[08/04/2022, 19:31:38] [HB Supervisor] Started Homebridge v1.4.0 with PID: 2516
[08/04/2022, 19:31:40] Loaded config.json with 0 accessories and 3 platforms.
[08/04/2022, 19:31:40] Loaded 3 cached accessories from cachedAccessories.
[08/04/2022, 19:31:41] ---
[08/04/2022, 19:31:43] Loaded plugin: homebridge-blink-for-home@3.9.0
[08/04/2022, 19:31:43] Registering platform 'homebridge-blink-for-home.Blink'
[08/04/2022, 19:31:43] ---
[08/04/2022, 19:31:44] Loaded plugin: homebridge-camera-ffmpeg@3.1.4
[08/04/2022, 19:31:44] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[08/04/2022, 19:31:44] ---
[08/04/2022, 19:31:44] Loaded plugin: homebridge-config-ui-x@4.42.0
[08/04/2022, 19:31:44] Registering platform 'homebridge-config-ui-x.config'
[08/04/2022, 19:31:44] ---
[08/04/2022, 19:31:44] Loading 3 platforms...
[08/04/2022, 19:31:44] [Config] Initializing config platform...
[08/04/2022, 19:31:44] [Config] Running in Service Mode
[08/04/2022, 19:31:44] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[08/04/2022, 19:31:44] [Blink] Initializing Blink platform...
[08/04/2022, 19:31:44] [Camera FFmpeg] [WyzePatio] Configuring unbridged accessory...
[08/04/2022, 19:31:44] [Blink] Init Blink
Setup Payload:
X-HM://00246MC2H4RXT
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

┌────────────┐     
│ xxx-xx-xxxx  |   
└────────────┘     
[08/04/2022, 19:31:45] WyzePatio ED0D is running on port 36549.
[08/04/2022, 19:31:45] Please add [WyzePatio ED0D] manually in Home app. Setup Code : xxx-xx-xxxx
[08/04/2022, 19:31:45] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 306F) is running on port 51382.
[08/04/2022, 19:31:46] [Blink] ADD: Blink:Network:95669
[08/04/2022, 19:31:46] [Blink] ADD: Blink:Network:95669:Camera:236341
[08/04/2022, 19:31:46] [Blink] ADD: Blink:Network:95669:Camera:236364
[08/04/2022, 19:31:47] [Blink] Blink Westchester Blink - Blink Westchester Blink Arm: Manual Arm
[08/04/2022, 19:31:47] [Blink] Blink Westchester Blink - Blink Westchester Blink Arm: ✅
[08/04/2022, 19:31:47] [Blink] Blink Backyard - Temperature: 10.6°C
[08/04/2022, 19:31:47] [Blink] Blink Backyard - Enabled: ✅
[08/04/2022, 19:31:47] [Blink] Blink Front Door Cam - Temperature: 8.9°C
[08/04/2022, 19:31:47] [Blink] Blink Westchester Blink - Blink Westchester Blink Armed (Target): ✅
[08/04/2022, 19:31:47] [Blink] Blink Westchester Blink - Blink Westchester Blink Armed (Current): ✅

**Comment by AtriskAlpha** [comment]
[08/04/2022, 19:41:28] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 306F) is running on port 51382.
[08/04/2022, 19:41:28] [Blink] GET /api/v3/accounts/89438/homescreen @30
[08/04/2022, 19:41:29] [Blink] ====== START BLINK DEBUG ======
[08/04/2022, 19:41:29] [Blink] POST /api/v5/account/login @null
[08/04/2022, 19:41:29] [Blink] GET /user @1
[08/04/2022, 19:41:29] [Blink] GET /api/v3/accounts/89438/homescreen @0
[08/04/2022, 19:41:30] [Blink] login()
[08/04/2022, 19:41:30] [Blink] {
    "account": {
        "account_id": 1001,
        "account_verification_required": false,
        "amazon_account_linked": true,
        "client_id": 1002,
        "client_trusted": true,
        "client_verification_required": false,
        "country_required": false,
        "new_account": false,
        "phone_verification_required": false,
        "region": "ap",
        "require_trust_client_device": true,
        "tier": "u004",
        "user": {"country": "US", "user_id": 1003},
        "user_id": 1003,
        "verification_channel": "phone"
    },
    "allow_pin_resend_seconds": 90,
    "auth": {"token": "XXXX9999"},
    "force_password_reset": false,
    "lockout_time_remaining": 0,
    "phone": {"country_calling_code": "1", "last_4_digits": "5555", "number": "+1******5555", "valid": true},
    "verification": {"email": {"required": false}, "phone": {"channel": "sms", "required": true}}
}
[08/04/2022, 19:41:30] [Blink] getAccountHomescreen()
[08/04/2022, 19:41:30] [Blink] {
    "accessories": {"rosie": [], "storm": []},
    "account": {"id": 1001, "amazon_account_linked": true, "email_verification_required": true, "email_verified": true},
    "app_updates": {"code": 103, "message": "OK", "update_available": false, "update_required": false},
    "cameras": [
        {
            "id": 3001,
            "name": "Camera 1",
            "network_id": 2001,
            "updated_at": "2022-04-08T18:31:09+00:00",
            "created_at": "2019-01-06T18:39:24+00:00",
            "battery": "ok",
            "enabled": true,
            "fw_version": "2.151",
            "issues": [],
            "local_storage_compatible": false,
            "local_storage_enabled": false,
            "revision": null,
            "serial": "B0000001",
            "signals": {"battery": 3, "lfr": 2, "temp": 51, "wifi": 4},
            "snooze": false,
            "snooze_time_remaining": null,
            "status": "done",
            "thumbnail": "/media/u004/account/1001/network/2001/camera/3001/clip_Liu7Ogxo_2022_04_08__18_26PM",
            "type": "xt",
            "usage_rate": false
        },
        {
            "id": 3002,
            "name": "Camera 2",
            "network_id": 2001,
            "updated_at": "2022-04-08T18:35:37+00:00",
            "created_at": "2019-01-06T18:42:37+00:00",
            "battery": "ok",
            "enabled": false,
            "fw_version": "2.151",
            "issues": [],
            "local_storage_compatible": false,
            "local_storage_enabled": false,
            "revision": null,
            "serial": "B0000002",
            "signals": {"battery": 3, "lfr": 5, "temp": 48, "wifi": 5},
            "snooze": false,
            "snooze_time_remaining": null,
            "status": "done",
            "thumbnail": "/media/u004/account/1001/network/2001/camera/3002/clip_t4xAeapG_2022_04_08__17_26PM",
            "type": "xt",
            "usage_rate": false
        }
    ],
    "chimes": [],
    "device_limits": {"camera": 10, "chime": 5, "doorbell": 10, "doorbell_button": 2, "owl": 10, "siren": 5, "total_devices": 20},
    "doorbell_buttons": [],
    "doorbells": [
        {
            "id": 5154,
            "name": "Front Doorbell",
            "network_id": 2001,
            "updated_at": "2022-04-08T18:24:11+00:00",
            "created_at": "2021-12-25T15:34:18+00:00",
            "battery": "ok",
            "changing_mode": false,
            "config_out_of_sync": false,
            "doorbell_mode": "lfr",
            "enabled": true,
            "fw_version": "12.55",
            "issues": [],
            "local_storage_compatible": false,
            "local_storage_enabled": false,
            "onboarded": true,
            "revision": "00",
            "serial": "G8T1SJ00140302MT",
            "signals": {"battery": 3, "lfr": 5, "wifi": 5},
            "snooze": false,
            "snooze_time_remaining": null,
            "status": "done",
            "thumbnail": "/api/v3/media/accounts/1001/networks/2001/lotus/5154/thumbnail/thumbnail.jpg?ts=1647542379&ext=",
            "type": "lotus"
        },
        {
            "id": 6418,
            "name": "Side Doorbell",
            "network_id": 2001,
            "updated_at": "2022-04-08T17:32:01+00:00",
            "created_at": "2022-01-08T19:38:39+00:00",
            "battery": "ok",
            "changing_mode": false,
            "config_out_of_sync": false,
            "doorbell_mode": "lfr",
            "enabled": true,
            "fw_version": "12.55",
            "issues": [],
            "local_storage_compatible": false,
            "local_storage_enabled": false,
            "onboarded": true,
            "revision": "00",
            "serial": "G8T1SJ001403027R",
            "signals": {"battery": 3, "lfr": 5, "wifi": 2},
            "snooze": false,
            "snooze_time_remaining": null,
            "status": "done",
            "thumbnail": "/api/v3/media/accounts/1001/networks/2001/lotus/6418/thumbnail/thumbnail.jpg?ts=1647542386&ext=",
            "type": "lotus"
        }
    ],
    "entitlements": {"updated_at": "2022-03-16T03:50:30+00:00"},
    "networks": [
        {
            "id": 2001, "name": "BatCave", "updated_at": "2022-04-08T17:31:58+00:00",
            "created_at": "2019-01-06T18:35:32+00:00", "armed": true, "dst": true, "lv_save": false,
            "time_zone": "America/New_York"
        }
    ],
    "owls": [],
    "sirens": [],
    "subscriptions": {"updated_at": "2022-03-16T03:50:30+00:00"},
    "sync_modules": [
        {
            "id": 5001, "name": "Sync Module 1", "network_id": 2001, "updated_at": "2022-04-07T23:19:20+00:00",
            "created_at": "2021-12-25T15:24:36+00:00", "enable_temp_alerts": true, "fw_version": "15.9.12",
            "last_hb": "2022-04-08T18:40:42+00:00", "local_storage_compatible": true, "local_storage_enabled": false,
            "local_storage_status": "active", "onboarded": true, "revision": "00", "serial": "D0000001",
            "status": "online", "subtype": "billy", "type": "sm2", "wifi_strength": 5
        }
    ],
    "tiv_lock_enable": true,
    "tiv_lock_status": {"locked": true},
    "video_stats": {"auto_delete_day_options": [3, 7, 14, 30, 60], "auto_delete_days": 7, "storage": 0},
    "whats_new": {"updated_at": 20210204, "url": "https://updates.blinkforhome.com/"}
}
[08/04/2022, 19:41:30] [Blink] getMediaChange()
[08/04/2022, 19:41:30] [Blink] GET /api/v1/accounts/89438/media/changed?since=1970-01-01T00:00:01.000Z&page=1 @60
[08/04/2022, 19:41:30] [Blink] {"limit": 500, "media": [], "purge_id": 2659298960, "refresh_count": 0}
[08/04/2022, 19:41:30] [Blink] getAccount()
[08/04/2022, 19:41:30] [Blink] {
    "id": 1003, "name": "", "account_id": 1001, "updated_at": "2021-04-16T03:40:39+00:00",
    "created_at": "2019-01-06T18:34:39+00:00", "country_calling_code": "1", "country_id": "US",
    "email": "user@example.com", "force_password_reset": false, "locale": "en_US", "owner": true,
    "phone_number": "5555555555", "phone_verification_channel": "sms", "phone_verification_required": true,
    "phone_verified": true, "pin_created_at": null, "pin_failures": 0, "reset_expiration": null, "temp_units": "f",
    "time_zone": "US/Eastern", "timezone_id": 169, "type": "regular", "user_access": "write",
    "verification_channel": "phone", "verification_required": true, "verified": true
}
[08/04/2022, 19:41:30] [Blink] getAccountNotifications()
[08/04/2022, 19:41:30] [Blink] GET /api/v1/accounts/89438/notifications/configuration @1
[08/04/2022, 19:41:30] [Blink] {
    "notifications": {
        "accessory_connected": true, "accessory_disconnected": true, "accessory_low_battery": true, "bandwidth": true,
        "battery_dead": true, "camera_offline": true, "camera_usage": true, "doorbell": true, "general": true,
        "lfr": true, "local_storage": true, "low_battery": true, "motion": true, "scheduling": true,
        "sync_module_offline": true, "temperature": true, "wifi": true
    }
}
[08/04/2022, 19:41:30] [Blink] getAccountOptions()
[08/04/2022, 19:41:30] [Blink] GET /api/v1/account/options @1
[08/04/2022, 19:41:30] [Blink] {
    "amazon_account_linking": "available",
    "amazon_account_linking_enabled": true,
    "breadcrumbs": [],
    "c2s_clip_list_limit": 1000,
    "catalina_app_enabled": true,
    "legacy_account_mini": true,
    "lv_save": [],
    "owl_app_enabled": true,
    "sm2_app_enabled": true,
    "snapshot_app_enabled": true,
    "trial_cancellation_enabled": true,
    "trial_opt_in_eligible": false
}
[08/04/2022, 19:41:30] [Blink] getAccountStatus()
[08/04/2022, 19:41:30] [Blink] GET /api/v3/account/89438/status @1
[08/04/2022, 19:41:30] [Blink] {"account": {"id": 1001, "verification_required": false}, "client": {"id": 1002, "verification_required": false}}
[08/04/2022, 19:41:30] [Blink] getAppStatus()
[08/04/2022, 19:41:30] [Blink] GET /api/v1/fw/app/update_check?serial=IOS_8854 @1
[08/04/2022, 19:41:30] [Blink] {}
[08/04/2022, 19:41:30] [Blink] getBlinkAppVersion()
[08/04/2022, 19:41:30] [Blink] GET /api/v1/version @1
[08/04/2022, 19:41:30] [Blink] {"code": 103, "message": "OK", "update_available": false, "update_required": false}
[08/04/2022, 19:41:30] [Blink] getBlinkRegions()
[08/04/2022, 19:41:30] [Blink] GET /regions?locale=US @1
[08/04/2022, 19:41:30] [Blink] {
    "mode": "manual",
    "preferred": "usu010",
    "regions": {
        "e007": {"display_order": 4, "dns": "e007", "friendly_name": "Europe", "registration": true},
        "sg": {"display_order": 5, "dns": "prsg", "friendly_name": "Southeast Asia", "registration": true},
        "usu006": {"display_order": 3, "dns": "u006", "friendly_name": "United States - WEST", "registration": true},
        "usu010": {"display_order": 1, "dns": "u010", "friendly_name": "United States - CENTRAL", "registration": true},
        "usu020": {"display_order": 2, "dns": "u020", "friendly_name": "United States - EAST", "registration": true}
    }
}
[08/04/2022, 19:41:30] [Blink] getBlinkStatus()
[08/04/2022, 19:41:30] [Blink] GET https://blinkstatus.net/api/v1/prod @1
[08/04/2022, 19:41:31] [Blink] {
    "check_interval": 60,
    "message": "The Blink Cloud service is operating normally.",
    "message_code": 0,
    "message_params": [],
    "monitor_last_update": "2022-04-08T18:41:27Z",
    "next_check_time": "2022-04-08T18:41:32Z",
    "url": ""
}
[08/04/2022, 19:41:31] [Blink] getBlinkSupport()
[08/04/2022, 19:41:31] [Blink] GET /api/v2/support/ob_phone/ @1
[08/04/2022, 19:41:31] [Blink] {"phone_number": "7813325465", "start_day": 1, "start_hour_utc": 15, "stop_day": 5, "stop_hour_utc": 23}
[08/04/2022, 19:41:31] [Blink] getClientOptions()
[08/04/2022, 19:41:31] [Blink] GET /api/v1/accounts/89438/clients/882859/options @1
[08/04/2022, 19:41:31] [Blink] {"options": "{}"}
[08/04/2022, 19:41:31] [Blink] getNetworks()
[08/04/2022, 19:41:31] [Blink] GET /networks @1
[08/04/2022, 19:41:31] [Blink] {
    "networks": [
        {
            "id": 2001, "name": "BatCave", "account_id": 1001, "updated_at": "2022-04-08T17:31:58+00:00",
            "created_at": "2019-01-06T18:35:32+00:00", "arm_string": "Armed", "armed": true, "autoarm_geo_enable": false,
            "autoarm_time_enable": false, "busy": false, "camera_error": false, "description": "", "dst": true,
            "encryption_key": null, "feature_plan_id": null, "lfr_channel": 0, "locale": "", "location_id": null,
            "lv_mode": "relay", "network_key": "1y892f9xympwHIo=", "network_origin": "normal", "ping_interval": 60,
            "sm_backup_enabled": true, "storage_total": 0, "storage_used": 0, "sync_module_error": false,
            "time_zone": "America/New_York", "video_count": 0, "video_destination": "server", "video_history_count": 4000
        }
    ],
    "summary": {"2001": {"name": "BatCave", "onboarded": true}}
}
[08/04/2022, 19:41:31] [Blink] getSirens()
[08/04/2022, 19:41:31] [Blink] GET /sirens @1
[08/04/2022, 19:41:31] [Blink] GET /sirens (404 Not Found)
[08/04/2022, 19:41:31] [Blink] GET /sirens
[08/04/2022, 19:41:31] [Blink] Error: GET /sirens (404 Not Found)
    at BlinkAPI._request (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:342:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlinkAPI.get (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:228:16)
    at BlinkAPI.getSirens (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:1114:16)
    at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:469:25)
    at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:507:13)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[08/04/2022, 19:41:31] [Blink] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:472:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:507:13)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[08/04/2022, 19:41:31] [Blink] Error: Blink Authentication failed.
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:116:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[08/04/2022, 19:41:31] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

**Comment by AtriskAlpha** [comment]
BEST LOG SHOWING THE ISSUE....


[08/04/2022, 19:50:07] WyzePatio ED0D is running on port 44729.
[08/04/2022, 19:50:07] Please add [WyzePatio ED0D] manually in Home app. Setup Code: XXX-XX-XXXX
[08/04/2022, 19:50:07] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 306F) is running on port 51382.
[08/04/2022, 19:50:09] [Blink] ADD: Blink:Network:95669
[08/04/2022, 19:50:09] [Blink] ADD: Blink:Network:95669:Camera:236341
[08/04/2022, 19:50:10] [Blink] ADD: Blink:Network:95669:Camera:236364
[08/04/2022, 19:50:25] [Blink] Blink Backyard - Enabled: ✅
[08/04/2022, 19:50:25] [Blink] Blink Westchester Blink - Blink Westchester Blink Arm: ✅
[08/04/2022, 19:50:26] [Blink] Blink Front Door Cam - Temperature: 8.9°C
[08/04/2022, 19:50:26] [Blink] Blink Backyard - Temperature: 10.6°C
[08/04/2022, 19:50:55] [Blink] Blink Backyard - Privacy Mode: ✅
[08/04/2022, 19:50:56] [Blink] Blink Front Door Cam - Privacy Mode: ✅
[08/04/2022, 19:50:56] [Blink] Blink Westchester Blink - Blink Westchester Blink Arm: Manual Arm
[08/04/2022, 19:50:58] [Blink] Blink Front Door Cam - Enabled: ✅
[08/04/2022, 19:50:58] [Blink] Blink Front Door Cam - Enabled: ✅
[08/04/2022, 19:51:08] [Blink] Blink Front Door Cam - Enabled: ❌
[08/04/2022, 19:51:15] [Blink] TypeError: Cannot read properties of undefined (reading 'proxyServer')
    at BlinkCameraDelegate.handleStreamRequest (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/blink-camera-deligate.js:240:31)
    at RTPStreamManagement._handleStopStream (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:963:19)
    at HAPConnection.emit (node:events:402:35)
    at HAPConnection.onTCPSocketClose (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:679:10)
    at Socket.emit (node:events:390:28)
    at TCP.<anonymous> (node:net:687:12)
[08/04/2022, 19:51:50] [Blink] Blink Front Door Cam - Refreshing snapshot
[08/04/2022, 19:51:54] [Blink] Blink Backyard - Temperature: 11.1°C
[08/04/2022, 19:51:54] [Blink] Blink Front Door Cam - Enabled: ✅
[08/04/2022, 19:51:59] [Blink] TypeError: Cannot read properties of undefined (reading 'proxyServer')
    at BlinkCameraDelegate.handleStreamRequest (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/blink-camera-deligate.js:240:31)
    at RTPStreamManagement._handleStopStream (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:963:19)
    at HAPConnection.emit (node:events:402:35)
    at HAPConnection.onTCPSocketClose (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:679:10)
    at Socket.emit (node:events:390:28)
    at TCP.<anonymous> (node:net:687:12)
[08/04/2022, 19:52:05] [Blink] LiveView Stream: undefined
[08/04/2022, 19:52:05] Error: Audio was enabled but not supplied in PrepareStreamResponse!
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1124:13)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1094:16
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at BlinkCameraDelegate.prepareStream (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/blink-camera-deligate.js:132:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[08/04/2022, 19:52:05] Got SIGTERM, shutting down Homebridge...
<img width="1156" alt="Screen Shot 2022-04-08 at 2 53 41 PM" src="https://user-images.githubusercontent.com/103281769/162503889-68789222-acc4-4083-86ab-d4cdd0e82f3e.png">
<img width="1055" alt="Screen Shot 2022-04-08 at 2 54 25 PM" src="https://user-images.githubusercontent.com/103281769/162504027-033ab917-2e78-4932-aa36-2cb3158eff6b.png">

**Comment by AtriskAlpha** [comment]
DEBUG INFO.

    'app-build': 'IOS_2202111015',
    Locale: 'en_US',
    'x-blink-time-zone': 'America/New York',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'kRBu-GZtk9hzcJchkIloHA'
  }
}
[10/04/2022, 15:54:31] [Blink] 200 
[10/04/2022, 15:54:31] [Blink] {
  'account-id': '89438',
  'client-id': '533115',
  'client-verified': '1',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sun, 10 Apr 2022 14:54:31 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'user-id': '89432',
  vary: 'Accept-Encoding',
  via: '1.1 193d4441ee6d312fd234f2d28e48c110.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'IQ0-LWLsp73wB1EEM6nLPsAFnxYt2HTBnQ-sqJddxDHLUEtfm42CMQ==',
  'x-amz-cf-pop': 'PHL50-C1',
  'x-blink-served-by': 'i-0311325d3ad6c11bf',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/04/2022, 15:54:31] [Blink] {
    "amazon_account_linking": "available",
    "amazon_account_linking_enabled": true,
    "breadcrumbs": [],
    "c2s_clip_list_limit": 1000,
    "catalina_app_enabled": true,
    "legacy_account_mini": true,
    "lv_save": [],
    "owl_app_enabled": true,
    "sm2_app_enabled": true,
    "snapshot_app_enabled": true,
    "trial_cancellation_enabled": true,
    "trial_opt_in_eligible": false
}
[10/04/2022, 15:54:31] [Blink] {
    "amazon_account_linking": "available",
    "amazon_account_linking_enabled": true,
    "breadcrumbs": [],
    "c2s_clip_list_limit": 1000,
    "catalina_app_enabled": true,
    "legacy_account_mini": true,
    "lv_save": [],
    "owl_app_enabled": true,
    "sm2_app_enabled": true,
    "snapshot_app_enabled": true,
    "trial_cancellation_enabled": true,
    "trial_opt_in_eligible": false
}
[10/04/2022, 15:54:31] [Blink] getAccountStatus()
[10/04/2022, 15:54:31] [Blink] GET /api/v3/account/89438/status @1
[10/04/2022, 15:54:31] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/2202111015 CFNetwork/1331.0.7 Darwin/21.4.0',
    'app-build': 'IOS_2202111015',
    Locale: 'en_US',
    'x-blink-time-zone': 'America/New York',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'kRBu-GZtk9hzcJchkIloHA'
  }
}
[10/04/2022, 15:54:31] [Blink] 200 
[10/04/2022, 15:54:31] [Blink] {
  'account-id': '89438',
  'client-id': '533115',
  'client-verified': '1',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sun, 10 Apr 2022 14:54:31 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'user-id': '89432',
  vary: 'Accept-Encoding',
  via: '1.1 193d4441ee6d312fd234f2d28e48c110.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'WOA2DF-eerbcYofml3zqLw9zt3BwRiVzzp_PBKMlCceS2zzjBPFuEg==',
  'x-amz-cf-pop': 'PHL50-C1',
  'x-blink-served-by': 'i-016c8fe3c114209be',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/04/2022, 15:54:31] [Blink] {"account": {"id": 89438, "verification_required": false}, "client": {"id": 533115, "verification_required": false}}
[10/04/2022, 15:54:31] [Blink] {"account": {"id": 1001, "verification_required": false}, "client": {"id": 1002, "verification_required": false}}
[10/04/2022, 15:54:31] [Blink] getAppStatus()
[10/04/2022, 15:54:31] [Blink] GET /api/v1/fw/app/update_check?serial=IOS_8854 @1
[10/04/2022, 15:54:31] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/2202111015 CFNetwork/1331.0.7 Darwin/21.4.0',
    'app-build': 'IOS_2202111015',
    Locale: 'en_US',
    'x-blink-time-zone': 'America/New York',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'kRBu-GZtk9hzcJchkIloHA'
  }
}
[10/04/2022, 15:54:31] [Blink] 200 
[10/04/2022, 15:54:31] [Blink] {
  'account-id': '89438',
  'client-id': '533115',
  'client-verified': '1',
  'content-length': '2',
  'content-type': 'application/json',
  date: 'Sun, 10 Apr 2022 14:54:31 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'user-id': '89432',
  via: '1.1 193d4441ee6d312fd234f2d28e48c110.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'QAPxvtq5nKrZN84Nzvk72LlOq4VCVBegCtgrxHOsDvC6QYo2BV-hCA==',
  'x-amz-cf-pop': 'PHL50-C1',
  'x-blink-served-by': 'i-01dbe2398e47dae77',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/04/2022, 15:54:31] [Blink] {}
[10/04/2022, 15:54:31] [Blink] {}
[10/04/2022, 15:54:31] [Blink] getBlinkAppVersion()
[10/04/2022, 15:54:31] [Blink] GET /api/v1/version @1
[10/04/2022, 15:54:31] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/2202111015 CFNetwork/1331.0.7 Darwin/21.4.0',
    'app-build': 'IOS_2202111015',
    Locale: 'en_US',
    'x-blink-time-zone': 'America/New York',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'kRBu-GZtk9hzcJchkIloHA'
  }
}
[10/04/2022, 15:54:31] [Blink] 200 
[10/04/2022, 15:54:31] [Blink] {
  'client-verified': '0',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sun, 10 Apr 2022 14:54:31 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  vary: 'Accept-Encoding',
  via: '1.1 193d4441ee6d312fd234f2d28e48c110.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'gzy6wdNETPrsTLzGffi7uh27Dt8XhKI7KsOjjsElKiG8sWwg28fXHg==',
  'x-amz-cf-pop': 'PHL50-C1',
  'x-blink-served-by': 'i-0c68b4aaf91ac69cc',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/04/2022, 15:54:31] [Blink] {"code": 103, "message": "OK", "update_available": false, "update_required": false}
[10/04/2022, 15:54:31] [Blink] {"code": 103, "message": "OK", "update_available": false, "update_required": false}
[10/04/2022, 15:54:31] [Blink] getBlinkRegions()
[10/04/2022, 15:54:31] [Blink] GET /regions?locale=US @1
[10/04/2022, 15:54:31] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/2202111015 CFNetwork/1331.0.7 Darwin/21.4.0',
    'app-build': 'IOS_2202111015',
    Locale: 'en_US',
    'x-blink-time-zone': 'America/New York',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'kRBu-GZtk9hzcJchkIloHA'
  }
}
[10/04/2022, 15:54:31] [Blink] 200 
[10/04/2022, 15:54:31] [Blink] {
  'client-verified': '0',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sun, 10 Apr 2022 14:54:31 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  vary: 'Accept-Encoding',
  via: '1.1 193d4441ee6d312fd234f2d28e48c110.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'BASNlEDbdco7R1JMpxMVpm8jfFQnIiePk8s612fA1LEchtvUQ-sBew==',
  'x-amz-cf-pop': 'PHL50-C1',
  'x-blink-served-by': 'i-0531ecf639774cb18',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/04/2022, 15:54:31] [Blink] {
    "mode": "manual",
    "preferred": "usu010",
    "regions": {
        "e007": {"display_order": 4, "dns": "e007", "friendly_name": "Europe", "registration": true},
        "sg": {"display_order": 5, "dns": "prsg", "friendly_name": "Southeast Asia", "registration": true},
        "usu006": {"display_order": 3, "dns": "u006", "friendly_name": "United States - WEST", "registration": true},
        "usu010": {"display_order": 1, "dns": "u010", "friendly_name": "United States - CENTRAL", "registration": true},
        "usu020": {"display_order": 2, "dns": "u020", "friendly_name": "United States - EAST", "registration": true}
    }
}
[10/04/2022, 15:54:31] [Blink] {
    "mode": "manual",
    "preferred": "usu010",
    "regions": {
        "e007": {"display_order": 4, "dns": "e007", "friendly_name": "Europe", "registration": true},
        "sg": {"display_order": 5, "dns": "prsg", "friendly_name": "Southeast Asia", "registration": true},
        "usu006": {"display_order": 3, "dns": "u006", "friendly_name": "United States - WEST", "registration": true},
        "usu010": {"display_order": 1, "dns": "u010", "friendly_name": "United States - CENTRAL", "registration": true},
        "usu020": {"display_order": 2, "dns": "u020", "friendly_name": "United States - EAST", "registration": true}
    }
}
[10/04/2022, 15:54:31] [Blink] getBlinkStatus()
[10/04/2022, 15:54:31] [Blink] GET https://blinkstatus.net/api/v1/prod @1
[10/04/2022, 15:54:31] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/2202111015 CFNetwork/1331.0.7 Darwin/21.4.0',
    'app-build': 'IOS_2202111015',
    Locale: 'en_US',
    'x-blink-time-zone': 'America/New York',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'kRBu-GZtk9hzcJchkIloHA'
  }
}
[10/04/2022, 15:54:32] [Blink] 200 OK
[10/04/2022, 15:54:32] [Blink] {
  'accept-ranges': 'bytes',
  connection: 'Close',
  'content-length': '225',
  'content-type': 'application/json',
  date: 'Sun, 10 Apr 2022 14:54:32 GMT',
  etag: '"6252efa3-e1"',
  'last-modified': 'Sun, 10 Apr 2022 14:54:27 GMT',
  server: 'nginx/1.15.0'
}
[10/04/2022, 15:54:32] [Blink] {
    "check_interval": 60,
    "message": "The Blink Cloud service is operating normally.",
    "message_code": 0,
    "message_params": [],
    "monitor_last_update": "2022-04-10T14:54:27Z",
    "next_check_time": "2022-04-10T14:54:32Z",
    "url": ""
}
[10/04/2022, 15:54:32] [Blink] {
    "check_interval": 60,
    "message": "The Blink Cloud service is operating normally.",
    "message_code": 0,
    "message_params": [],
    "monitor_last_update": "2022-04-10T14:54:27Z",
    "next_check_time": "2022-04-10T14:54:32Z",
    "url": ""
}
[10/04/2022, 15:54:32] [Blink] getBlinkSupport()
[10/04/2022, 15:54:32] [Blink] GET /api/v2/support/ob_phone/ @1
[10/04/2022, 15:54:32] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/2202111015 CFNetwork/1331.0.7 Darwin/21.4.0',
    'app-build': 'IOS_2202111015',
    Locale: 'en_US',
    'x-blink-time-zone': 'America/New York',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'kRBu-GZtk9hzcJchkIloHA'
  }
}
[10/04/2022, 15:54:32] [Blink] 200 
[10/04/2022, 15:54:32] [Blink] {
  'client-verified': '0',
  'content-length': '2',
  'content-type': 'application/json',
  date: 'Sun, 10 Apr 2022 14:54:32 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  via: '1.1 193d4441ee6d312fd234f2d28e48c110.cloudfront.net (CloudFront)',
  'x-amz-cf-id': '79qdLiw2TdPCr_HABA_SuDO7q-rqw03DsbE5JGnSvb3i8_4NjmJCQw==',
  'x-amz-cf-pop': 'PHL50-C1',
  'x-blink-served-by': 'i-0c58132cd96e62516',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/04/2022, 15:54:32] [Blink] {}
[10/04/2022, 15:54:32] [Blink] {}
[10/04/2022, 15:54:32] [Blink] getClientOptions()
[10/04/2022, 15:54:32] [Blink] GET /api/v1/accounts/89438/clients/533115/options @1
[10/04/2022, 15:54:32] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/2202111015 CFNetwork/1331.0.7 Darwin/21.4.0',
    'app-build': 'IOS_2202111015',
    Locale: 'en_US',
    'x-blink-time-zone': 'America/New York',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'kRBu-GZtk9hzcJchkIloHA'
  }
}
[10/04/2022, 15:54:32] [Blink] 200 
[10/04/2022, 15:54:32] [Blink] {
  'account-id': '89438',
  'client-id': '533115',
  'client-verified': '1',
  'content-length': '16',
  'content-type': 'application/json',
  date: 'Sun, 10 Apr 2022 14:54:32 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'user-id': '89432',
  via: '1.1 193d4441ee6d312fd234f2d28e48c110.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'FTYnYn4jmubxuC2VgKiinF_r55-XzzKT0nZyYmuo6oBXUFkfQBdgWg==',
  'x-amz-cf-pop': 'PHL50-C1',
  'x-blink-served-by': 'i-0c68b4aaf91ac69cc',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/04/2022, 15:54:32] [Blink] {"options": "{}"}
[10/04/2022, 15:54:32] [Blink] {"options": "{}"}
[10/04/2022, 15:54:32] [Blink] getNetworks()
[10/04/2022, 15:54:32] [Blink] GET /networks @1
[10/04/2022, 15:54:32] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/2202111015 CFNetwork/1331.0.7 Darwin/21.4.0',
    'app-build': 'IOS_2202111015',
    Locale: 'en_US',
    'x-blink-time-zone': 'America/New York',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'kRBu-GZtk9hzcJchkIloHA'
  }
}
[10/04/2022, 15:54:32] [Blink] 200 
[10/04/2022, 15:54:32] [Blink] {
  'account-id': '89438',
  'client-id': '533115',
  'client-verified': '1',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sun, 10 Apr 2022 14:54:32 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'user-id': '89432',
  vary: 'Accept-Encoding',
  via: '1.1 193d4441ee6d312fd234f2d28e48c110.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'm5kBHMhwVMaKXHu4j-KU3GeI-6ddI64TOaLlfmJ8YWe7ihxLCJWidw==',
  'x-amz-cf-pop': 'PHL50-C1',
  'x-blink-served-by': 'i-06eba6ff42c6181e9',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/04/2022, 15:54:32] [Blink] {
    "networks": [
        {
            "id": 95669, "name": "Westchester Blink", "account_id": 89438, "updated_at": "2022-04-08T17:31:58+00:00",
            "created_at": "2019-01-06T18:35:32+00:00", "arm_string": "Armed", "armed": true, "autoarm_geo_enable": false,
            "autoarm_time_enable": false, "busy": false, "camera_error": false, "description": "", "dst": true,
            "encryption_key": null, "feature_plan_id": null, "lfr_channel": 0, "locale": "", "location_id": null,
            "lv_mode": "relay", "network_key": "1y892f9xympwHIo=", "network_origin": "normal", "ping_interval": 60,
            "sm_backup_enabled": true, "storage_total": 0, "storage_used": 0, "sync_module_error": false,
            "time_zone": "America/New_York", "video_count": 0, "video_destination": "server", "video_history_count": 4000
        }
    ],
    "summary": {"95669": {"name": "Westchester Blink", "onboarded": true}}
}
[10/04/2022, 15:54:32] [Blink] {
    "networks": [
        {
            "id": 2001, "name": "BatCave", "account_id": 1001, "updated_at": "2022-04-08T17:31:58+00:00",
            "created_at": "2019-01-06T18:35:32+00:00", "arm_string": "Armed", "armed": true, "autoarm_geo_enable": false,
            "autoarm_time_enable": false, "busy": false, "camera_error": false, "description": "", "dst": true,
            "encryption_key": null, "feature_plan_id": null, "lfr_channel": 0, "locale": "", "location_id": null,
            "lv_mode": "relay", "network_key": "1y892f9xympwHIo=", "network_origin": "normal", "ping_interval": 60,
            "sm_backup_enabled": true, "storage_total": 0, "storage_used": 0, "sync_module_error": false,
            "time_zone": "America/New_York", "video_count": 0, "video_destination": "server", "video_history_count": 4000
        }
    ],
    "summary": {"2001": {"name": "BatCave", "onboarded": true}}
}
[10/04/2022, 15:54:32] [Blink] getSirens()
[10/04/2022, 15:54:32] [Blink] GET /sirens @1
[10/04/2022, 15:54:32] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/2202111015 CFNetwork/1331.0.7 Darwin/21.4.0',
    'app-build': 'IOS_2202111015',
    Locale: 'en_US',
    'x-blink-time-zone': 'America/New York',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'kRBu-GZtk9hzcJchkIloHA'
  }
}
[10/04/2022, 15:54:32] [Blink] 404 
[10/04/2022, 15:54:32] [Blink] {
  'client-verified': '0',
  'content-length': '11',
  'content-type': 'text/html;charset=utf-8',
  date: 'Sun, 10 Apr 2022 14:54:32 GMT',
  server: 'nginx + Phusion Passenger',
  status: '404 Not Found',
  via: '1.1 193d4441ee6d312fd234f2d28e48c110.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'HlgqHRZTM3_HrUc0d5sZ7sC6fjy7LbRbR9cGa_yOYW8ZPMKvHvw3Hw==',
  'x-amz-cf-pop': 'PHL50-C1',
  'x-blink-served-by': 'i-0431eb6cf5055cf04',
  'x-cache': 'Error from cloudfront',
  'x-cascade': 'pass',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-powered-by': 'Phusion Passenger',
  'x-xss-protection': '1; mode=block'
}
[10/04/2022, 15:54:32] [Blink] GET /sirens
[10/04/2022, 15:54:32] [Blink] GET /sirens (404 Not Found)
[10/04/2022, 15:54:32] [Blink] GET /sirens
[10/04/2022, 15:54:32] [Blink] Error: GET /sirens (404 Not Found)
    at BlinkAPI._request (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:342:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlinkAPI.get (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:228:16)
    at BlinkAPI.getSirens (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:1114:16)
    at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:469:25)
    at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:507:13)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[10/04/2022, 15:54:32] [Blink] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:472:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:507:13)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[10/04/2022, 15:54:32] [Blink] Error: Blink Authentication failed.
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:116:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[10/04/2022, 15:54:32] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

**Comment by colinbendell** [comment]
Ok. I pushed a bunch of updates today to fix the streaming. Even though live view isn't fully supported, homekit still needs a valid stream to avoid these crashes. this should fix your issues with 3.9.1

**Comment by AtriskAlpha** [comment]
Thank you so much will let you know how it goes.


Scott Seifert
216-338-1486 Mobile
***@***.***

**Comment by AtriskAlpha** [comment]
Did update, no issues as far as install... Also, homebridge is not crashing anymore when viewing the live stream. The live stream does not work but, we have progress and I don't really need this for anything other than convenience, so I can wait for the next update…. Thumbnails are previewing, they seem to show up really fast and accurately all the time now. But the streaming still doesn't work, screenshots below.

I have two early model cameras and then two of the new doorbells. Don't care about the doorbells, they don't show up at all and I don't care. Just really paying with home bridge, and thank you for all your work...

[10/04/2022, 22:17:04] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[10/04/2022, 22:17:04] [Homebridge UI] Sending SIGTERM to Homebridge
[10/04/2022, 22:17:04] Got SIGTERM, shutting down Homebridge...
[10/04/2022, 22:17:09] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[10/04/2022, 22:17:14] [HB Supervisor] Restarting Homebridge...
[10/04/2022, 22:17:14] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/04/2022, 22:17:14] [HB Supervisor] Started Homebridge v1.4.0 with PID: 9517
[10/04/2022, 22:17:16] Loaded config.json with 0 accessories and 3 platforms.
[10/04/2022, 22:17:17] Loaded 3 cached accessories from cach

[10/04/2022, 22:17:17] ---
[10/04/2022, 22:17:20] Loaded plugin: homebridge-blink-for-home@3.9.1
[10/04/2022, 22:17:20] Registering platform 'homebridge-blink-for-home.Blink'
[10/04/2022, 22:17:20] ---
[10/04/2022, 22:17:20] Loaded plugin: homebridge-camera-ffmpeg@3.1.4
[10/04/2022, 22:17:20] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[10/04/2022, 22:17:20] ---
[10/04/2022, 22:17:20] Loaded plugin: homebridge-config-ui-x@4.42.0
[10/04/2022, 22:17:20] Registering platform 'homebridge-config-ui-x.config'
[10/04/2022, 22:17:20] ---
[10/04/2022, 22:17:20] Loading 3 platforms...
[10/04/2022, 22:17:20] [Config] Initializing config platform...
[10/04/2022, 22:17:20] [Config] Running in Service Mode
[10/04/2022, 22:17:20] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[10/04/2022, 22:17:20] [Blink] Initializing Blink platform...
[10/04/2022, 22:17:20] [Camera FFmpeg] [WyzePatio] Configuring unbridged accessory...
[10/04/2022, 22:17:20] [Blink] Init Blink
[10/04/2022, 22:17:21] [Blink] POST /api/v5/account/login @null
Setup Payload:
X-HM://00246MC2H4RXT
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 431-46-393 │     
    └────────────┘     
                       
[10/04/2022, 22:17:21] WyzePatio ED0D is running on port 46453.
[10/04/2022, 22:17:21] Please add [WyzePatio ED0D] manually in Home app. Setup Code: 431-46-393
[10/04/2022, 22:17:21] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 306F) is running on port 51382.
[10/04/2022, 22:17:22] [Blink] GET /api/v3/accounts/89438/homescreen @30
[10/04/2022, 22:17:22] [Blink] ADD: Blink:Network:95669
[10/04/2022, 22:17:22] [Blink] ADD: Blink:Network:95669:Camera:236341
[10/04/2022, 22:17:22] [Blink] ADD: Blink:Network:95669:Camera:236364
[10/04/2022, 22:17:22] [Blink] Blink Westchester Blink - Blink Westchester Blink Arm: Manual Arm
[10/04/2022, 22:17:22] [Blink] Blink Westchester Blink - Blink Westchester Blink Arm: ✅
[10/04/2022, 22:17:22] [Blink] Blink Backyard - Temperature: 11.1°C
[10/04/2022, 22:17:22] [Blink] Blink Backyard - Enabled: ✅
[10/04/2022, 22:17:22] [Blink] Blink Backyard - Privacy Mode: ✅
[10/04/2022, 22:17:22] [Blink] Blink Front Door Cam - Temperature: 8.9°C
[10/04/2022, 22:17:22] [Blink] Blink Front Door Cam - Enabled: ✅
[10/04/2022, 22:17:22] [Blink] Blink Front Door Cam - Privacy Mode: ✅
[10/04/2022, 22:17:52] [Blink] GET /api/v3/accounts/89438/homescreen @30
[10/04/2022, 22:17:56] [Blink] Blink Backyard - LiveView: /usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/../offline.png
[10/04/2022, 22:17:56] [Blink] Blink Backyard - LiveView START (1280x720, 30 fps, 299 kbps, 1378 mtu)...
[10/04/2022, 22:18:07] [Blink] GET /media/u004/account/89438/network/95669/camera/236364/clip_Iy7DfqvU_2022_04_10__21_12PM.jpg @1
[10/04/2022, 22:18:08] [Blink] Blink Backyard - LiveView STOP
[10/04/2022, 22:18:10] [Blink] Blink Front Door Cam - LiveView: /usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/../offline.png
[10/04/2022, 22:18:10] [Blink] Blink Front Door Cam - LiveView START (1280x720, 30 fps, 299 kbps, 1378 mtu)...
[10/04/2022, 22:18:22] [Blink] GET /api/v3/accounts/89438/homescreen @30
[10/04/2022, 22:18:26] [Blink] Blink Front Door Cam - LiveView STOP

<img width="1121" alt="Screen Shot 2022-04-10 at 5 22 06 PM" src="https://user-images.githubusercontent.com/103281769/162640458-7cbe9f36-9f64-4efb-9467-7c3ec537217f.png">
<img width="1121" alt="Screen Shot 2022-04-10 at 5 23 09 PM" src="https://user-images.githubusercontent.com/103281769/162640472-7d707b88-7946-4391-87d8-f52f1e3fd50a.png">
