### ISSUE TITLE
Version 3.5.13 - image is still not updated

### ISSUE THREAD

**Issue by Ron0815** [colinbendell/homebridge-blink-for-home#12]
Unfortunately the update in version 3.5.13 did not solve my problem. The image is still not updated/refreshed after the first start.

_Originally posted by @Ron0815 in https://github.com/colinbendell/homebridge-blink-for-home/issues/10#issuecomment-720629755_

**Comment by swadhwani51** [comment]
Having the same issue.  I cant seem to get the cameras to display because it states the cameras are in privacy mode yet i turned it off in the advanced settings globally

**Comment by Ron0815** [comment]
Could this Problem be caused by the 2-factor-authentication in the blink-App? When I open the thumbnail of the blink-camera in homekit I recieve an e-mail by blink, where I am asked to enter a code in the App:

>>„We've detected a login attempt on your Blink account from:
Device: iPhone 11 Pro 
Device Name: unknown 
To confirm this was you, please enter the verification code below in your app now.“<<

**Comment by Ron0815** [comment]
Okay, that‘s it. After I entered the Code I got by mail, the thumbnail updated every 30 sec.

**Comment by Ron0815** [comment]
Could the interval of refreshing the still-image be shortened?

**Comment by Ron0815** [comment]
Changing the time interval in the settings is always ignored. The still image is only refreshed every 45 seconds

**Comment by mlavio829** [comment]
Hi,
I seem to be getting an error: [11/6/2020, 12:51:46 PM] [Blink] [Video] ffmpeg exited with code: 1 and signal: null (error)
Hasn't updated since the first time it turned on (even though every 45 seconds it refreshes)

**Comment by colinbendell** [comment]
> Could the interval of refreshing the still-image be shortened?

I've added an option to allow you to shorten the image refresh. in 3.5.14

**Comment by colinbendell** [comment]
> Changing the time interval in the settings is always ignored. The still image is only refreshed every 45 seconds

This is for the data polling which doesn't change the thumbnail refresh.

**Comment by colinbendell** [comment]
> I seem to be getting an error: [11/6/2020, 12:51:46 PM] [Blink] [Video] ffmpeg exited with code: 1 and signal: null (error)
> Hasn't updated since the first time it turned on (even though every 45 seconds it refreshes)
@mlavio829 this should be fixed in 3.5.14 with a more explicit dependency for ffmpeg

**Comment by Ron0815** [comment]
Oops, what's that? After the update to the new version 3.5.14, instead of an image the thumbnail shows "Camera disabled". What can I do?

**Comment by aje89** [comment]
> Oops, what's that? After the update to the new version 3.5.14, instead of an image the thumbnail shows "Camera disabled". What can I do?

Same here

**Comment by Jeremesk** [comment]
I don’t have the new « camera disabled » message, but I still have the « ffmpeg exited with code: 1 and signal: null » error in 3.5.14

**Comment by colinbendell** [comment]
> Oops, what's that? After the update to the new version 3.5.14, instead of an image the thumbnail shows "Camera disabled". What can I do?

You can enable the camera two ways. In the Blink app, under the settings you can enable the camera. Or in homekit, you can go into the camera settings (click on the preview, settings) then select the accessories and enable it:

![image](https://user-images.githubusercontent.com/1622597/98450780-9d2a0400-210d-11eb-85f1-5a851dad2570.png)
![image](https://user-images.githubusercontent.com/1622597/98450782-9ef3c780-210d-11eb-8f81-998bc171242c.png)

**Comment by colinbendell** [comment]
>  ffmpeg exited with code: 1 and signal: null » error in 3.5.14

yea, I'm going to guess you have an XT2 or the new indoor/outdoor devices? I don't have this hardware so I haven't been able to reverse engineer the protocol yet. Just ordered, so I'll let you know when I figure it out.

**Comment by Jeremesk** [comment]
> yea, I'm going to guess you have an XT2 or the new indoor/outdoor devices? I don't have this hardware so I haven't been able to reverse engineer the protocol yet. Just ordered, so I'll let you know when I figure it out.

Good guess! I have a XT2.
Ok, I hope you’ll find a way to make it work. Thanks!

**Comment by griffisc306** [comment]
Would this apply to the mini as well?

**Comment by Ron0815** [comment]
The image is back. Thank you!
